export const skillset = [
    { id: 1, content: "Semantic & accessible HTML" },
    { id: 2, content: "Error handling" },
    { id: 3, content: "Git" },
    { id: 4, content: "Responsive Web Design" },
    { id: 5, content: "React" },
    { id: 6, content: "Github Pull Requests Review" },
    { id: 7, content: "JavaScript: ES6+" },
    { id: 8, content: "React Hooks" },
    { id: 9, content: "NPM" },
    { id: 10, content: "Working with API (fetch, axios)" },
    { id: 11, content: "Redux (Toolkit)" },
    { id: 12, content: "Immutability" },
    { id: 13, content: "Promises, Async/Await" },
    { id: 14, content: "Redux - Saga" },
    { id: 15, content: "Markdown" },
    { id: 16, content: "Debugging" },
    { id: 17, content: "React Router" },
    { id: 18, content: "Scrum" },
    { id: 19, content: "CSS BEM convention" },
    { id: 20, content: "CSS Flexbox" },
    { id: 21, content: "CSS Grid" },
    { id: 22, content: "Styled Components" },
    { id: 23, content: "Markdown" },
    { id: 24, content: "Teamwork" },
    { id: 25, content: "Figma" },
    { id: 26, content: "Trello" },
    { id: 27, content: "C#" },
];